### ISSUE TITLE
Changes with ESP-12S Module

### ISSUE THREAD

**Issue by edmalho** [liebman/AnalogClock#14]
The 12S already has some pull-up resistors, specifically on the CH-PD, GPIO0 and GPIO15. It also lacks a 470 resistor in series on REST.
What modifications do I need to make?
I'm thinking of removing  the R9, R12 and R13. Good idea?

**Comment by liebman** [comment]
Did you get a chance to try a 12S?  On a separate project I had issues with reset, or maybe CH-PD not behaving the same.  I'd love to hear if you made this work.

**Comment by liebman** [comment]
Yes you can leave at least those three resistors off.  Don't forget to change the flash mode to DIO. It does however have issues with the reset circuit in that the reset button, at least as designed, does not function.  As a work around you will should be able remove power and apply power with the button pressed instead of reset..... I'm also not sure that deep sleep will work correctly as its also associated with RST.....

**Comment by liebman** [comment]
I'm thinking that the reset issue (RST pin having zero effect) may be due to my modules being defective or fakes.  Will have to acquire some from another source.

**Comment by liebman** [comment]
I've just ordered some different esp-12s's and I'll test them again.

**Comment by edmalho** [comment]
Sorry for the very late response. i didn't build boards yet, my free time went out the window but i would love to ear something from you when you test it

**Comment by liebman** [comment]
@edmalho OK - my new esp-12s modules work perfectly. So I'm assuming that the previous modules were fakes. So yes you should be able to leave those three resistors off.
